= 802.1 Qbv Time-Aware Shaping Demonstration Overview

:toc: macro
:idprefix:
:idseparator: -

ifndef::site-gen-antora[]
toc::[]
endif::[]

The purpose of this demonstration is to show how IEEE 802.1Qbv Time Aware Shaping (TAS) can ensure low latencies and no dropped frames for critical traffic when network links are over-subscribed, while also demonstrating the limits of TAS with a scenario that it is unable to protect against.

All scenarios within this demonstration share a common topology.  

* EP~1~ provides the IEEE 802.1AS reference clock, as well as producing 4 independent scheduled, critical traffic items.  
* EP~2~ produces 3 streams of prioritized traffic and 1 stream of non-prioritized vanilla Ethernet traffic.  Note that it is not a time receiver, nothing on this node is synchronized to the network schedule.
* EP~3~ is a time receiver, as well as receiving the traffic from EP~1~ and EP~2~.  
* For the scenarios that involve overlapping shared priority traffic, EP~2~ adds an additional 4 scheduled, critical traffic items that share the same schedule and priority levels as those from EP~1~.

.TAS Demo Topology
image::topo-layer-base.drawio.svg[]

Scheduled traffic refers to traffic that is transmit at a fixed offset from the start of each network cycle.  
Streaming traffic refers to traffic that is allocated a percentage of the line rate, and is not synchronized to the network cycle.


== Scenario Details

The scenarios assume that EP~n~ is connected to port n of the switch.  If using different port assignments, adjust the instructions accordingly.

* Precise definitions of some of the terminology used in the table below, specific to these TAS demonstrations:
** Switch TAS State (Enabled / Disabled) 
*** This is referring to whether or not the egress ports on the switch have TAS gates enabled or disabled.  
*** The endpoints producing scheduled traffic should always be configured to produce the traffic at the appropriate time, regardless of the switch configuration.
** Scheduled Traffic Configuration (Overlapping, shared priority levels / Non-Overlapping, no shared priority levels)
*** In the non-overlapping case, there is a single endpoint EP~1~ generating scheduled traffic.  
*** In the overlapping case, there are two endpoints EP~1~ and EP~2~ generating scheduled traffic, with identical priority levels and timing of transmission of the frames from the endpoint
** Receiving End-Point Link (Saturated / Not Saturated)
*** In the not saturated version, the aggregate bandwidth of EP~1~ and EP~2~ are well under 1 Gbps line rate.  
**** EP~1~ generates 4 separate traffic classes, each at a different priority level 1-4, each producing a single packet of a fixed size (64 bytes) every 1ms, each offset by 250 micro-seconds from the previous.  
**** EP~2~ generates 3 streams of traffic using priority levels 5-7, each utilizing 10% of the line rate, fixed 64 byte packets.
**** EP~2~ also generates 1 stream of vanilla Ethernet (no priority specified), utilizing 50% of the line rate, with random packet sizes from 64 to 1518 bytes.
*** In the saturated version, the aggregate bandwidth exceeds 1 Gbps line rate
**** EP~1~ is unchanged
**** EP~2~, the vanilla Ethernet is produced at 70% of line rate.

.Time Aware Shaping Scenarios
|===  
|Scenario |Switch TAS State |Scheduled Traffic Configuration |Receiving End-Point Link |Description |Expected Results
|1
|Disabled
|Non-Overlapping, no shared priority levels
|Not Saturated
|This is a simple demo, with no switch quality of service features, showing how by over-provisioning the network, vanilla Ethernet can work well.
|Low but slightly elevated latencies on critical traffic compared to w/ TAS.  Overall low latencies and no frame drops across all traffic items.

|2
|Disabled
|Non-Overlapping, no shared priority levels
|Saturated
|This is an off-nominal extension of scenario 1, where the vanilla Ethernet device is 'babbling" resulting in over-subscribing the link to the receiving end-point.  
|Given there are no QoS features enabled, it is expected this scenario will result in increased latencies and frame drops of all traffic items, including the critical traffic.

|3
|Disabled
|Overlapping, shared priority levels
|Not Saturated
|This scenario has 2 transmitting nodes, both transmitting critical traffic of the same priority level which is likely to be a common occurrence in realistic flight networks.  For example, all GNC sensors may sample data at the same time and have it ready to transmit at the same time, and be mapped to the same priority level.  It is possible the TAS schedule will offset them at the transmitting end-point, but for a simplified network that may not happen resulting in the two nodes overlapping.  
|Slightly increased latencies for the critical traffic, no dropped frames.

|4
|Disabled
|Overlapping, shared priority levels
|Saturated
|This is an off-nominal extension of scenario 3.  In this case, one of the producers of critical traffic is over-producing traffic.  
|Significantly increased latencies and frame drops on all traffic items.

|5
|Enabled
|Non-Overlapping, no shared priority levels
|Not Saturated
|This is a repeat of scenario 1, but with TAS gating enabled in the switch.  This is a baseline nominal scenario for TAS.
|Minor reduction in latency of what was already low-latency critical traffic (due to lack of contention with streaming traffic), otherwise not too much difference from scenario 1.  

|6
|Enabled
|Non-Overlapping, no shared priority levels
|Saturated
|This is an off-nominal extension of scenario 5, and shows how TAS is able to prevent lower priority traffic (in this case, the vanilla Ethernet traffic) from affecting the higher priority traffic, through the use of TAS gating.  
|Significantly increased latencies and frame drops only on the babbling vanilla Ethernet stream.  The critical traffic in particular should have latencies unaffected.

|7
|Enabled
|Overlapping, shared priority levels
|Not Saturated
|This is a repeat of scenario 3, but with TAS gating enabled in the switch.  In this scenario, the critical traffic from the 2 nodes is scheduled to be output at the same time, and share a time window on the switch.  
|Slightly increased latencies for critical traffic (due to contention between the 2 nodes) compared to the non-overlapping version.

|8
|Enabled
|Overlapping, shared priority levels
|Saturated
|This final scenario is an off-nominal extension of scenario 7, and demonstrates how there are some faults that TAS by itself cannot deal with.  In this case, the 2 transmitting nodes shared a priority level, and one of them will 'babble' critical traffic.  In an ideal Spacecraft network, this should not interfere with the critical traffic from any other nodes.  However, TAS by itself is not able to address that.  A future demonstration will show how IEEE P802.1Qci (Per-Stream Filtering and Policing) addresses this fault case.
|Significantly increased latencies and frame drops of all traffic, including critical traffic from the end-point that is behaving correctly.  

|===

For each scenario, frame drop and latency statistics per traffic item are reported.

For each scenario, the general approach is to model it in Pegase, implement it in each hardware venue, export the results back to Pegase, and compare the actual vs model.


----
