= TSN Scenarios

A set of Time-Sensitive Networking (TSN) scenarios implemented in various venues for the purposes of demonstration and application development.

== Keysight (Ixia) Sessions

The `ixn.py` script is a tool for creating and running traffic with the Keysight traffic emulator. Some basic notes on using this script:

=== Configuration YAML files

There are two configuration files that determine the traffic scenario to run with the Keysight.

The first configuration file sets up the topology, and has the following general format:

[source, yaml]
----
endpoints:
  ep1:              # Arbitrary name of endpoint. Can be whatever the user wants
    port_num: 5     # The index of the physical RJ45/Optical connector on the keysight
    device_groups:  # Groups of devices
      eth1:         # An ethernet stack. This must start with 'eth'
        mac: '00:11:01:00:00:01'
        ip: '100.1.0.1'
        ipv4: True
        gateway_prefix: 24
        gateway: '10.1.0.10'
        resolve_gateway: False
  ep3:
    port_num: 7
    device_groups:
      eth1:
        mac: '00:11:01:00:00:03'
        ip: '100.1.0.3'
        ipv4: True
        gateway_prefix: 24
        gateway: '10.1.0.10'
        resolve_gateway: False
      eth2:
        mac: '00:11:01:00:00:04'
        ip: '100.1.0.4'
        ipv4: True
        gateway_prefix: 24
        gateway: '10.1.0.10'
        resolve_gateway: False
  ...
----

The second configuration file describes the traffic items:


[source, yaml]
----
traffic_items:
  - name: "Traffic1"
    type: "ipv4"
    src:
      - "ep1"
    dst:
      - "ep3.eth1.ip"  # This is a valid endpoint because ep3 has an eth1 ip defined
    udp: True
    dst_port: 1000
    tx_rate: 10000
  - name: "Traffic2"
    type: "ipv4"
    src:
      - "ep1.eth3.ip"  # NOTE: This is an invalid endpoint because there is no eth3 in the ep1 topology above
    dst:
      - "ep3.eth1.ip"
    udp: True
    dst_port: 1100
    tx_rate: 11000
  ...
----

**NOTE: The list of `src` and `dst` in the traffic file must match an endpoint path in the topology. See the NOTE in the example above**


=== Create a session

`uv run tools/ixn/ixn.py create --topology scenarios/ixnetwork/<scenario>/<topology_yaml>  --traffic scenarios/ixnetwork/<scenario>/<traffic_yaml> --session-name <session_name> --dry-run`

The option `--clean` can be used to wipe any existing session with the same name before creating a new one

=== Run a session

`uv run tools/ixn/ixn.py run --session-name <session_name> --run-time-sec <time_in_sec>`

If the session cannot be found, it will return an error. The default run time is 10s, but if you set it to 0, then it will leave the session running. It would then need to be stopped with the `stop` command

=== Stopping a session

`uv run tools/ixn/ixn.py stop --session_name <session_name>`

If the session cannot be found, it will return an error.
