= Common Issues

If a scenario is not executing as expected, some things to check for:

TODO: Add more information about what to look for.  Maybe a section on symptoms (based on switch stats, traffic latencies / frame drops, etc), with likely causes.

== Symptom-based tips
* Looking at the switch stats can help a great deal with tracking down what is happening.  

== General hardware configuration tips
* Verify the hardware configuration matches how the ports are physically connected.
** Switch
*** Many items are based on port.  For example, for time-aware shaping, it has to be enabled on the specific egress port.  For prioritization to work, classification needs to be enabled on each ingress port.
*** The default switch configuration has port 1-4 enable port classification, and port 3 is the egress port that all the traffic should be going to.  
*** Consider if it would be easier to modify the hardware settings, or change the physical cabling to match the scenario instructions.
** Traffic Generators
*** For the Keysight, this is relatively simple - on the overview screen, check each port is mapped to the correct physical port in the chassis.
* Virtual LANs (VLANs)
** Switch
*** Ensure the VLAN settings match the base switch configuration, unless otherwise specified for the specific scenario.
** Traffic Generators
*** Be sure to use the right protocol stack - for the Keysight for example, there is one for Ethernet w/ VLAN and one for Ethernet w/o VLAN
**** VLAN is enabled, with ID set to 0 for devices / protocol stacks generating prioritized traffic.  (You may see frames being filtered in the switch stats if VLAN is some other value)
**** VLAN is disabled for the time sync (transmitter and receiver) and vanilla ethernet devices / protocol stacks
* Switch CoS Settings
** In certain scenarios where VLAN priorities impact packet scheduling (i.e. Time Aware Shaping), after enabling TAS on the switch, latencies for specific traffic items may be higher than anticipated (often by an order of magnitude).
** This is due to VLAN priority ordering being such that there can be a priority lower than vanilla ethernet (priority ethernet). In the ethernet standard, this is priority 1. 
** This means that setting a traffic item priority 1 ultimately gives it lower priority than vanilla ethernet.
** The solution is scenario-dependent. For the majority of scenarios, make sure that you are not using VLAN priority 1, unless you intend a lower priority than vanilla ethernet.
*** For the TAS demo, make sure that you have followed the CoS settings as outlined in xref:802.1Qbv/emulation.adoc#detailed-switch-configuration[the keysight documentation for 802.1Qbv scenario 1].

== Harware-specific tips
* Keysight
** Try regenerating and applying traffic changes.  The tool sometimes does this automatically, but there are some cases where it does not.  Safest is to simply always perform both of these steps after making any changes and before starting the test.  
* Microchip iStax TSN switch
** The management port (last port) is treated like any other port, meaning various QoS and TSN features can be applied to that port, which can make the web ui inaccessible.  For example when defining a stream, do not select the last port as one of the ports to match to.  
*** If this happens, the remote serial connection (rsc ngatsnsw1, for example) can be used to recover.  There is some separate documentation on the equipment page for the switch for how to use the remote serial connection, and what kinds of commands can be sent.
*** Try "show running-config"
*** Look at management port: Gigabit Ethernet 1/1 and see if anything stands out that would interfere
** There have been occasions where the TAS gate config won't become active
*** Monitor page will show it is enabled, but no GCL defined, even though there is one on the config page
*** It isn't clear the exact series of steps that got it to work when this has happened, but when it eventually worked, traffic generators / time transmitter were halted, a switch config file that setup the gates was loaded, and then the time transmitter was started.  As soon as PTP was going it looks like the config change happened.  However, that same series of steps had been previous tried without success, so it isn't clear what may have been different when it eventually worked.
