= Getting Started

== Device Reservation

The TSN switches that we use are shared resources, and since they can be accessed over management interfaces that allow multiple users, we need to make sure we don't stomp on each other when we are using them. In the absence of a more sophisticated way to manage this, we require that the devices be "reserved" via Outlook calendar invites. The following emails have been created for you to send invitations using Outlook:

* `198-135A-hpsctsnsw0`
* `198-135A-hpsctsnsw1`
* `198-135A-hpsctsnsw2`
* `198-135A-hpsctsnsw3`
* `198-135A-ngatsnsw0`
* `198-135A-ngatsnsw1`
* `198-135A-ngatsnsw2`
* `198-135A-ngatsnsw3`

For the emulation venue:

* `198-135A-hpsctsnsw0` is connected to the Keysight ports 1-4
* `198-135A-ngatsnsw1` is connected to the Keysight ports 5-8

For now, unless otherwise agreed upon with Rob Donnelly, assume that the HPSC devices are off limits.

== Clone Repository

First clone this repository.

[source,sh]
----
git clone https://github.jpl.nasa.gov/hpsc/tsn-scenarios
cd tsn-scenarios
----

== Provision the Emulation Venue

Connect three ports of the Keysight Novus One Plus to ports 1-3 of an IStaX-based TSN switch.

== Setup Environment

Setup the environment by copying the provided `.env.example` to `.env`.

[source,sh]
----
cp .env.example .env
----

Then modify `.env` using your favorite editor.

[source,sh]
----
vim .env
----

Specify the IxNetwork host address, username, password, and ports.
Also specify the IStaX host address, username, and password.
Optionally specify a proxy for both.

== Create an SSH-SOCKS5 proxy
----
ssh -ND9999 aalab
----
See https://github.jpl.nasa.gov/pages/hpsc/lab/docs/main/network/remote-access/#start-an-ssh-socks-proxy[here] for more information.

== Run the Emulation Venue

[source,sh]
.Run all tests
----
cd scenarios/ixnetwork
uv run pytest
----

[source,sh]
.Run a subset of tests
----
cd scenarios/ixnetwork
uv run pytest 802.1Qci-stream-gate
----

[source,sh]
.Run a single test module
----
cd scenarios/ixnetwork
uv run pytest 802.1Qci-stream-gate/test_basic.py
----
