= Network Tap

== Setup

* Ubuntu 24.04.4 LTS
* https://www.profitap.com/profishark-1g-plus/[Using Profishark Profitap 1G+]
* Install the driver. Linux instructions are below.
* Plug in USB from tap to machine on a usb 3.0 port.
* Connect ethernet cable from a NIC to port A on tap. And other going from port B to the appropriate port on the switch.
* Use tap with either profishark manager or wireshark.
* **NOTE:** must be connected to a usb 3.0 port. It will not work on usb 2.0!

=== Linux Driver Install

Use the following commands:

[source,bash]
----
wget https://ubuntu.profitap.com/keys/public.key
sudo apt-key add public.key
sudo add-apt-repository https://ubuntu.profitap.com/
sudo apt-get update
----

After these commands, you should be able to see all the available drivers, using:

[source,bash]
----
apt-cache search profishark-linux
sudo apt-get install profishark-linux-driver-X.YY.0-ZZ
----

If the correct kernel driver does not exist, you'll have to build manually from source:

* Download source repo from https://drive.google.com/drive/folders/1Vf53Qk_-dYG_j1QjtKS4SrIRzbW8RQEO[here]
* From within driver source repo (v1.11.4):
** `make`
** `sudo make install`
** `sudo modprobe pt3usb`

=== Linux Profishark Manager

[source,bash]
----
sudo apt-get install profishark-manager
----

Run with: `/usr/bin/profishark/profishark-manager`

* If ssh-ing in, make sure to run with X11 forwarding `ssh -Y <hostname>`
** If using a mac, https://www.xquartz.org/[xQuartz] has been useful to display X-forwarded windows
* In order to sync time in the Timing tab check the following options and click save:
** Wait For Sync
** Force PPS Generation

== Using with Wireshark

* Download wireshark extcap tool from https://profishark.profitap.com/Linux/ExtcapToolWireshark/[here]
* Grab wireshark's extcap path
** help -> About Wireshark -> Folders -> Global Extcap path
** In our case its: `/usr/libexec/wireshark/extcap`
* Extract the tarball somewhere temporary: `tar xf profishark-extcap_1.3_linux64.tar.gz`
* Copy files to extcap dir: `sudo cp profishark-extcap* /usr/libexec/wireshark/extcap/`
* Restart wireshark and you should see profishark show up as an interface
* Had to also modify some permissions to get this to work:
** `sudo dpkg-reconfigure wireshark-common`
** `sudo usermod -aG wireshark <username>`
** You must logout and back in, or run `newgrp wireshark` for this to take effect

== Multiple taps

If using multiple taps, we can sync their time in the following way:

* Connect taps using PPS IN port via cable
* Set one of the taps to force PPS generation: check "Force PPS Generation" and "PPS port output"
* Set the other tap to "Wait for sync"
* Wait ~30s for sync to happen and "Timestamped sync" light to turn green on both taps
