#!/usr/bin/env -S uv run --script --quiet
# PYTHON_ARGCOMPLETE_OK
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "argcomplete>=3.5.3",
#   "python-dotenv>=1.1.1",
#   "requests[socks]>=2.32.4",
#   "jinja2>=3.1.6"
# ]
# ///

import argparse
import fileinput
from io import StringIO
import os
import sys
from http.cookiejar import CookieJar
import time
from typing import TextIO

import argcomplete
import dotenv
import jinja2
import requests

VERSION = "0.2.0"

ENVAR_PROXY = "ISTAXCFG_PROXY"

PortMap = list[dict[str, str]]


class ApplicationError(Exception):
    def __init__(self, message):
        super().__init__(message)


def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)


def parse_opts():
    parser = argparse.ArgumentParser(
        prog="istaxcfg",
        description="IStaX configuration tool",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {VERSION}")
    parser.add_argument("--username", "-u", default="admin", help="host username")
    parser.add_argument("--password", "-p", default="", help="host password")
    parser.add_argument(
        "--proxy",
        "-x",
        metavar="[HOST:]PORT",
        default=os.environ.get(ENVAR_PROXY),
        help="proxy requests through a SOCKS5 proxy. HOST part defaults to localhost.",
    )

    commands = parser.add_subparsers(dest="command")

    activate = commands.add_parser(
        "activate",
        help="activate a stored configuration",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    activate.add_argument("host", help="hostname or IP address of the switch")
    activate.add_argument(
        "filename",
        help="switch filename to activate",
    )

    download = commands.add_parser(
        "download",
        aliases=["dl"],
        help="download the running configuration",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    download.add_argument(
        "--output", "-o", help="output file"
    ).completer = (  # ty: ignore[unresolved-attribute] on completer
        argcomplete.FilesCompleter
    )
    download.add_argument(
        "--filename",
        "-f",
        default="running-config",
        help="switch filename to download",
    )
    download.add_argument("host", help="hostname or IP address of the switch")

    upload = commands.add_parser(
        "upload",
        aliases=["ul"],
        help="upload the running configuration",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    upload.add_argument(
        "--dry-run",
        "-n",
        action=argparse.BooleanOptionalAction,
        help="print config without uploading",
    )
    upload.add_argument(
        "--merge",
        "-m",
        action=argparse.BooleanOptionalAction,
        help="merge uploaded configuration with running configuration instead of replacing it",
    )
    upload.add_argument(
        "--filename",
        "-f",
        default="running-config",
        help="switch filename to upload to",
    )
    upload.add_argument("host", help="hostname or IP address of the switch")
    upload.add_argument(
        "files",
        nargs="*",
        help="configuration file, multiple files are concatenated.",
    ).completer = (  # ty: ignore[unresolved-attribute] on completer
        argcomplete.FilesCompleter
    )

    argcomplete.autocomplete(parser)

    return parser.parse_args()


def parse_proxy(proxy: str) -> str:
    if proxy.isdecimal():
        return f"localhost:{proxy}"
    else:
        return proxy


def create_session(opts) -> requests.Session:
    session = requests.Session()
    session.cookies = CookieJar()

    if opts.proxy:
        proxy = parse_proxy(opts.proxy)
        proxies = {
            "http": f"socks5h://{proxy}",
            "https": f"socks5h:/{proxy}",
        }
        session.proxies.update(proxies)

    return session


def istax_login(session: requests.Session, host: str, username: str, password: str):
    eprint("logging in...")
    data = {
        "user": username,
        "password": password,
    }

    response = session.post(f"http://{host}/login", data=data)
    if response.status_code != 200:
        raise ApplicationError(f"unable to login to '{host}'")


def istax_config_activate(session: requests.Session, host: str, filename: str):
    data = {
        "file_name": filename,
    }

    session.post(f"http://{host}/config/icfg_conf_activate", data=data)

    istax_config_activate_status(session, host)


def istax_config_download(session: requests.Session, host: str, filename: str):
    data = {
        "file_name": filename,
    }

    response = session.post(f"http://{host}/config/icfg_conf_download", data=data)
    print(response.text)


def istax_config_activate_status(session: requests.Session, host: str):
    eprint("activating configuration...", end="", flush=True)

    timeout = time.time() + 90
    while True:
        try:
            response = session.get(
                f"http://{host}/config/icfg_conf_activate", timeout=1
            )
        except requests.Timeout:
            if time.time() > timeout:
                raise ApplicationError("timed out waiting for response")
            time.sleep(3)
            eprint(".", end="", flush=True)
            continue
        firstline = response.text.partition("\n")[0]
        if firstline == "<html>":
            if time.time() > timeout:
                raise ApplicationError("timed out waiting for response")
            eprint(".", end="", flush=True)
            time.sleep(3)
            continue
        elif response.text.partition("\n")[0] == "DONE":
            eprint()
            eprint("activation complete")
            break
        else:
            raise ApplicationError(f"activation failed with:\n{response.text.strip()}")


def istax_config_upload(
    session: requests.Session, host: str, filename: str, merge: bool, config: TextIO
):
    data = {
        "file_name": filename,
        "merge": str(merge).lower(),
    }

    files = {
        "source_file": config,
    }
    eprint("uploading configuration...")
    session.post(f"http://{host}/config/icfg_conf_upload", data=data, files=files)

    if filename == "running-config":
        istax_config_activate_status(session, host)


def istax_get_port_map(session: requests.Session, host: str) -> PortMap:
    eprint("fetching port map...")
    data = {
        "method": "port.namemap.get",
        "id": "jsonrpc",
        "params": [],
    }
    # WORKAROUND: IStaX returns a bad response header (extraneous and malformed
    # HTTP status line).  This causes urllib to raise an internal exception
    # before it parses the content-length.  Because of this, the post call
    # below blocks until TCP timeout which takes a few seconds.  We can work
    # around this by forcing the server to close the connection after
    # responding with the following header.
    headers = {"Connection": "close"}

    response = session.post(f"http://{host}/json_rpc", json=data, headers=headers)

    data = response.json()
    ports = [transform_port_name(entry["key"]) for entry in data["result"]]
    return ports


def dummy_port_map() -> PortMap:
    return [{"name": f"DummyEthernet 1/{i}"} for i in range(1, 10)]


def transform_port_name(name: str) -> dict[str, str]:
    (speed, index) = name.split()
    match speed:
        case "Gi":
            return {"name": f"GigabitEthernet {index}"}
        case "10G":
            return {"name": f"10GigabitEthernet {index}"}
        case _:
            raise


def command_activate(opts):
    session = create_session(opts)
    istax_login(session, opts.host, opts.username, opts.password)
    istax_config_activate(session, opts.host, opts.filename)


def command_download(opts):
    session = create_session(opts)
    istax_login(session, opts.host, opts.username, opts.password)
    istax_config_download(session, opts.host, opts.filename)


def render_config(opts, ports: PortMap, config) -> StringIO:
    search_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "..", "scenarios", "istax")
    )
    loader = jinja2.FileSystemLoader(search_path)
    environment = jinja2.Environment(loader=loader, trim_blocks=True)
    template = environment.from_string(config.read())
    data = {"hostname": opts.host, "ports": ports}
    rendered_template = template.render(data)
    return StringIO(rendered_template)


def command_upload(opts):
    # Concat inputs and insure only one end statement
    config = StringIO()
    for line in fileinput.input(opts.files):
        if line != "end\n":
            config.write(line)
    config.write("end\n")
    config.seek(0)

    if opts.dry_run:
        ports = dummy_port_map()
    else:
        session = create_session(opts)
        istax_login(session, opts.host, opts.username, opts.password)
        ports = istax_get_port_map(session, opts.host)

    config = render_config(opts, ports, config)

    if opts.dry_run:
        print(config.read())
    else:
        istax_config_upload(session, opts.host, opts.filename, opts.merge, config)


def main():
    dotenv.load_dotenv()
    opts = parse_opts()
    match opts.command:
        case "activate":
            command_activate(opts)
        case "download":
            command_download(opts)
        case "upload":
            command_upload(opts)


if __name__ == "__main__":
    try:
        main()
    except (
        requests.exceptions.ConnectionError  # ty: ignore[unresolved-attribute] on exceptions
    ) as e:
        eprint("error: " + str(e))
        sys.exit(1)
    except ApplicationError as e:
        eprint("error: " + str(e))
        if e.__cause__ is not None:
            eprint(f"cause: {e.__cause__}")
        sys.exit(1)

# vim: ft=python
