= istaxcfg
:toc: macro

Manage configuration for IStaX network switches.

toc::[]

== Overview

istaxcfg provides powerful configuration management capabilities for network switches running the IStaX platform.

It allows configuration to be layered and templated.

=== Layering

Configuration can be split over multiple files to allow configuration to be organized into layers.

For example, a base layer can provide basic configuration that is common across all uses, a VLAN layer can configure the port VLANs, a time sync layer can setup 802.1AS, etc.
These layers can be reused across scenarios.
Changing a single layer will change all scenarios that use it.

=== Templating

Configurations can be templated to allow the same configuration to be used across more contexts.

There are two types on configuration:

* Instance based - Can be different across instances of the same switch type (e.g., hostname)
* Type based - Can be different across different types of switch (e.g., VSC5640EV vs EV23X71A)

== Usage

=== Download Configuration

[source,sh]
.Usage
----
istaxcfg download <host>
----

[source,console]
.Example
----
> istaxcfg download hpsctsnsw0 | grep hostname
hostname hpsctsnsw0
----

=== Upload Preview

The final configuration can be previewed without actually uploading it via the `--dry-run` option.

[source,sh]
.Usage
----
istaxcfg upload <host> <config-file>
----

==== Upload Preview Example

[listing]
.`example.cfg` file
----
hostname {{ hostname }}
----

[source,console]
.Example
----
> istaxcfg upload --dry-run my-istax-host example.cfg
hostname my-istax-host
----

=== Concatenate Multiple Config Partials

[source,sh]
.Usage
----
istaxcfg upload <host> <partial-config-file> [<partial-config-file>...]
----

[source,console]
.Example
----
istaxcfg upload hpsctsnsw0 scenario.cfg mirroring.cfg
----

== Advanced Usage

=== Use a SOCKS5 Proxy

[source,sh]
----
ssh -D 9999 jump-host
istaxcfg --proxy localhost:9999 download <host>
----

== Configuration Templating

The `istaxcfg upload` commands concatenates all configuration template input files then renders the concatenated template using the Jinja templating library.

=== Templating Syntax

See the Jinja https://jinja.palletsprojects.com/en/stable/templates/[Template Designer Documentation] for syntax documentation.

=== Templating Variables

The following template variables are provided:

* `hostname` -- the hostname of the IStaX host obtained from the `hostname` argument of the `istaxcfg upload` command.
* `ports` -- an array of port objects.
Each port object has the following members:
** `name` -- the internal name of the port.

=== Configuration Templating Example

Given the following configuration template:

[source]
.Example configuration template (`example.cfg`)
----
hostname {{ hostname }}

{% for port in ports[:-1] %}
interface {{ port.name }}
 switchport access vlan 2
!
{% endfor %}
----

And given the following port map:

[source,yaml]
.Example switch description
----
ports:
- name: 10GigabitEthernet 1/1
- name: 10GigabitEthernet 1/2
----

[NOTE]
====
`ports` is a list of all ports including the management port.

The management port can be referenced in templates with `port[-1]`.
All ports except the management port can be referenced in templates with `ports[:-1]`.
====

The following command line:

[source,sh]
.Example command line
----
istaxcfg upload myhostname example.cfg --dry-run
----

Will generate the following output:

[source]
.Example output
----
hostname myhostname

interface 10GigabitEthernet 1/1
 switchport access vlan 2
!
interface 10GigabitEthernet 1/2
 switchport access vlan 2
!
interface GigabitEthernet 1/1
 switchport access vlan 2
!
----

=== Templating Conventions

==== Layering

Scenario configurations should include lower layer configuration such that only the scenario configuration needs to be provided.

For example, an 802.1Qbv scenario configuration should include the 802.1AS configuration and the base configuration.

[listing]
.Example `802.1Qbv.conf`
----
{% include "base.conf" %}
{% include "802.1AS.conf" %}

...
----

==== Mixins

Configuration mixins are configuration files that can be optionally added for things like debug.

For example, a mixin could be created to optionally enable port mirroring.

[source,sh]
.Example
----
istaxcfg upload myistaxhost scenario.cfg mirroring.cfg
----

==== Ports

An array of ports is provided to the configuration template via the `ports` template variable.
This array contains all ports front and back.
By convention, the management port is always the last port.
Python array slice syntax can be used to target a subset of ports.

[source,python]
.Loop through all ports
----
{% for port in ports %}
interface {{ port.name }}
 ...
!
{% endfor %}
----

[source,python]
.Loop through front ports only
----
{% for port in ports[:-1] %}
interface {{ port.name }}
 ...
!
{% endfor %}
----

[source,python]
.Management port only
----
interface {{ port[-1].name }}
 ...
!
----

== Dependencies

* https://docs.astral.sh/uv/[UV]

== Development Dependencies

* https://just.systems/[Just]

== Development

[source,sh]
.Format
----
just format
----

[source,sh]
.Check
----
just check
----
