= 802.1 Qci Per Stream Filtering and Policing Demonstration Overview

:toc: macro
:idprefix:
:idseparator: -

ifndef::site-gen-antora[]
toc::[]
endif::[]

The purpose of this demonstration is to show how IEEE 802.1Qci Per Stream Filtering and Policing (PSFP) can drop frames according to a variety of rules to provide fault tolerance and ensure the frames critical to a mission's success are delivered with minimal latency and jitter.

PSFP consists of 3 main functions.  Note these rely heavily on the Stream Identification function, which has a separate scenario documentation page.  Those pages and the venue-specific instructions will cover how to map frames to streams in detail.

* *Flow Meter:* Policing the bandwidth of a stream
** Defines steady-state and burst thresholds for policing traffic rates.
** Supports guaranteed bandwidth (green) as well as best effort (yellow) thresholds.
* *Stream Gating:* Provides time-aware control of when frames are allowed to pass for a given stream
** Same concept as Time Aware Shaping, but applied at the stream level, rather than the egress priority queue level
** This can also be configured to permanently shut off the gate (until a mgmt command is sent to clear the error) under certain conditions such as a frame received at an unexpected time, or a frame received that is too large.
* *Stream filtering:* Ties everything together
** The stream ID, flow meter ID, and Stream Gate ID are mapped together, as well as additional SDU size filtering.
** Flow meters and Stream Gates can be re-used (mapped to multiple stream IDs).

== Demo Topology

All scenarios within this demonstration share a common topology.  

* EP~1~ provides the IEEE 802.1AS reference clock, as well as a variety of traffic dependening on the needs of the particular scenario.  
* EP~2~ produces additional traffic dependent on the needs of the particular scenario.  The primary reason to have 2 separate end points produce frames, is to show how the policing can be configured to police based on which port the frames are received on.  
* EP~3~ is a time receiver, as well as receiving the traffic from EP~1~ and EP~2~.  
* For the scenarios that involve overlapping shared priority traffic, EP~2~ adds an additional 4 scheduled, critical traffic items that share the same schedule and priority levels as those from EP~1~.

.PSFP Demo Topology
image::topo-layer-base.drawio.svg[]

Scheduled traffic refers to traffic that is transmit at a fixed offset from the start of each network cycle.  
Streaming traffic refers to traffic that is allocated a percentage of the line rate, and is not synchronized to the network cycle.

== Common Details

The scenarios as described below assume that EP~n~ is connected to port n+4 of the switch.  If using different port assignments, adjust the instructions accordingly.  The venue-specific instructions with screenshots that can be found in the navigation bar on the left, may also need to be adjusted depending on which switch ports are cabled to which end points.

Unless explicitly defined otherwise, for every scenario, every traffic item produced by the end points should be produced at a unique rate, using different power of 2's (100 Kbps, 200 Kbps, 400 Kbps, 800 Kbps, etc).  The flow meters should also be set to unique rates, and always lower than the slowest traffic production rate.  This guarantees that it is always clear which traffic items are being filtered, and by which flow meter.

Precise definitions of some of the terminology used in the table below, specific to these TAS demonstrations:

* Time slot.  This is TDMA terminology, for the window of time in which a device is allowed to transmit.  In our case we use this terminology when defining gate opening and closing times.  Each entry in a Gate Control List defines a time slot, with a specific starting and ending time relative to the start of the network cycle.

== Scenario Details


----
