project := "tsn-scenarios"

init:
    apptainer exec docker://antora/antora npm i @antora/lunr-extension

build:
    apptainer run docker://antora/antora antora-playbook-local.yml

serve:
    echo "Serving on http://localhost:8080"
    python3 -m http.server 8080 -d build/site

dev:
    #!/bin/sh
    watchexec just build &
    just serve &
    trap 'kill $(jobs -pr)' EXIT
    wait

archive:
    just init
    just build
    mkdir {{project}}
    mv build {{project}}
    tar czf {{project}}-$(git log -1 --format=format:%h-%cs).tar.gz {{project}}
    rm -rf {{project}}
